#!/usr/bin/env python3
"""
Generate a multi-link `demo_building_collision` Gazebo model from the manifest
written by `scripts/extract_demo_building_collision.py`.

Each convex hull becomes its own `<link>` with both `<collision>` and
(optional) `<visual>` referencing the same STL via a `model://` URI. Surface
parameters are tuned for ODE in Gazebo Classic so a fast-moving drone gets a
firm contact instead of sliding through the mesh.

Inputs:
  - --manifest data/demo_assets/collision_manifest.json
  - --model-dir gazebo_wind_plugin/models/demo_building_collision

Outputs:
  - <model-dir>/model.sdf (overwritten)
  - <model-dir>/model.config (created if missing or --force-config)
  - <model-dir>/meshes/<rel_path> (copied from manifest hulls)

The mesh URIs use `model://demo_building_collision/meshes/...` so the model is
location-independent under `GAZEBO_MODEL_PATH`.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import List


CONFIG_TEMPLATE = """<?xml version=\"1.0\"?>
<model>
  <name>demo_building_collision</name>
  <version>1.1</version>
  <sdf version=\"1.6\">model.sdf</sdf>
  <author>
    <name>WRF-OpenFOAM-Coupling</name>
  </author>
  <description>
    RBM-4 high-order collision proxy: convex-hull decomposition near hotspot {hotspots}.
    Generated by scripts/build_demo_collision_model.py from {manifest_path}.
  </description>
</model>
"""


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/demo_assets/collision_manifest.json"),
        help="Manifest JSON written by extract_demo_building_collision.py",
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        default=Path("gazebo_wind_plugin/models/demo_building_collision"),
        help="Output Gazebo model directory.",
    )
    parser.add_argument("--no-visual", action="store_true", help="Skip transparent visual overlays for hulls.")
    parser.add_argument("--no-mesh-copy", action="store_true", help="Do not copy hull STLs (assume already in place).")
    parser.add_argument("--force-config", action="store_true", help="Overwrite model.config if it already exists.")
    parser.add_argument("--alpha", type=float, default=0.25, help="Visual overlay alpha (0..1).")
    return parser


def render_link_sdf(link_name: str, mesh_uri: str, with_visual: bool, alpha: float) -> str:
    visual_block = (
        f"      <visual name=\"vis_{link_name}\">\n"
        f"        <geometry>\n"
        f"          <mesh>\n"
        f"            <uri>{mesh_uri}</uri>\n"
        f"          </mesh>\n"
        f"        </geometry>\n"
        f"        <material>\n"
        f"          <ambient>0.85 0.30 0.20 {alpha:.2f}</ambient>\n"
        f"          <diffuse>0.85 0.30 0.20 {alpha:.2f}</diffuse>\n"
        f"        </material>\n"
        f"        <cast_shadows>false</cast_shadows>\n"
        f"      </visual>\n"
        if with_visual
        else ""
    )
    return (
        f"    <link name=\"{link_name}\">\n"
        f"      <gravity>false</gravity>\n"
        f"      <kinematic>false</kinematic>\n"
        f"      <collision name=\"col_{link_name}\">\n"
        f"        <geometry>\n"
        f"          <mesh>\n"
        f"            <uri>{mesh_uri}</uri>\n"
        f"          </mesh>\n"
        f"        </geometry>\n"
        f"        <surface>\n"
        f"          <contact>\n"
        f"            <collide_bitmask>0x01</collide_bitmask>\n"
        f"            <ode>\n"
        f"              <max_vel>0.1</max_vel>\n"
        f"              <min_depth>0.001</min_depth>\n"
        f"            </ode>\n"
        f"          </contact>\n"
        f"          <friction>\n"
        f"            <ode>\n"
        f"              <mu>0.6</mu>\n"
        f"              <mu2>0.6</mu2>\n"
        f"            </ode>\n"
        f"          </friction>\n"
        f"          <bounce>\n"
        f"            <restitution_coefficient>0.05</restitution_coefficient>\n"
        f"            <threshold>0.5</threshold>\n"
        f"          </bounce>\n"
        f"        </surface>\n"
        f"      </collision>\n"
        f"{visual_block}"
        f"    </link>\n"
    )


def main() -> int:
    args = build_arg_parser().parse_args()
    if not args.manifest.is_file():
        print(f"manifest not found: {args.manifest}", file=sys.stderr)
        return 1
    manifest = json.loads(args.manifest.read_text())

    model_dir = args.model_dir
    model_dir.mkdir(parents=True, exist_ok=True)
    meshes_dir = model_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    manifest_dir = args.manifest.parent
    links: List[str] = []
    copied = 0
    for building in manifest.get("buildings", []):
        bid = building["id"]
        for k, hull in enumerate(building["hulls"]):
            rel = hull["rel_path"]
            link_name = f"b{bid:02d}_h{k:03d}"
            mesh_target = meshes_dir / Path(rel).name
            if not args.no_mesh_copy:
                src = manifest_dir / rel
                if not src.is_file():
                    print(f"[err] hull mesh missing: {src}", file=sys.stderr)
                    return 1
                shutil.copy2(src, mesh_target)
                copied += 1
            mesh_uri = f"model://demo_building_collision/meshes/{mesh_target.name}"
            links.append(render_link_sdf(link_name, mesh_uri, with_visual=not args.no_visual, alpha=args.alpha))

    if not links:
        print("[err] manifest has no hulls", file=sys.stderr)
        return 1

    sdf_text = (
        "<?xml version=\"1.0\" ?>\n"
        "<sdf version=\"1.6\">\n"
        "  <!--\n"
        "    Auto-generated by scripts/build_demo_collision_model.py.\n"
        "    Each convex hull is its own <link> with collide_bitmask=0x01 and ODE\n"
        "    surface tuning so a fast-moving drone gets a firm contact.\n"
        "  -->\n"
        "  <model name=\"demo_building_collision\">\n"
        "    <static>true</static>\n"
        "    <pose>0 0 0 0 0 0</pose>\n"
        + "".join(links)
        + "  </model>\n"
        "</sdf>\n"
    )
    sdf_path = model_dir / "model.sdf"
    sdf_path.write_text(sdf_text)
    print(f"[write] {sdf_path} ({len(links)} link(s); meshes copied={copied})")

    config_path = model_dir / "model.config"
    if args.force_config or not config_path.exists():
        config_path.write_text(
            CONFIG_TEMPLATE.format(
                hotspots=", ".join("(" + ",".join(f"{v:.0f}" for v in h) + ")" for h in manifest.get("hotspots", [])),
                manifest_path=str(args.manifest),
            )
        )
        print(f"[write] {config_path}")

    union_min = manifest.get("union_bbox_min")
    union_max = manifest.get("union_bbox_max")
    if union_min and union_max:
        print(
            f"[info] union bbox xy=({union_min[0]:.1f}..{union_max[0]:.1f}, "
            f"{union_min[1]:.1f}..{union_max[1]:.1f}) z=({union_min[2]:.1f}..{union_max[2]:.1f})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
